name: rooster
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  provider: ^4.1.3
  http: ^0.12.2
  simple_animations: ^2.2.1
  flare_flutter: ^2.0.3
  flutter_speed_dial: ^1.2.5
  autocomplete_textfield: ^1.7.3
  shared_preferences: ^0.5.8
  crypto: any
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.11
  open_file: ^3.0.1
  tutorial_coach_mark: ^0.5.1
  #dropdownfield: 1.0.3
  google_fonts: ^1.1.2
  flutter_typeahead: ^3.0.0-nullsafety.0
  #flash: ^2.0.3
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.0
  circular_profile_avatar: ^2.0.0
  flutter_easyloading: ^3.0.3
  fl_chart: ^0.40.2
  intl: ^0.17.0
  convex_bottom_bar: ^3.0.0
  bottom_navy_bar: ^5.6.0
  fab_circular_menu: ^1.0.2
  data_connection_checker: ^0.3.4
  flutter_launcher_icons: ^0.9.2
  intl_phone_field: ^3.0.1
  table_calendar: ^2.2.3
  flutter_slidable: ^0.5.7
  flutter_local_notifications: ^4.0.1+2
  cron:
  fluttertoast: ^8.0.9
  slimy_card: ^1.0.4
  neumorphic_container: ^0.0.1+2
  neuomorphic_container: ^2.0.3
  badges: ^2.0.3
  hover_effect: ^0.0.0
  percent_indicator: 4.2.0
  razorpay_flutter: ^1.3.0
  hand_signature: ^2.3.0+1

  #flash: ^2.0.5

  
  

flutter_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  
      

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/flight_bg.png
    - assets/images/drawer_header_background.png
    - assets/images/othercharge_background.gif
    - assets/anim/rooster.flr
    - assets/airportCode.json
    - assets/specialcode.json
    - assets/countrycode.json
    - assets/airlinecode.json
    - assets/wallet.gif
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: avenir
    fonts:
        - asset: assets/font/Avenir-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
