name: rooster
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  #old version
  http: ^0.12.1
  #http: ^0.13.5
  simple_animations: ^5.0.0+3
  flare_flutter: ^3.0.2
  #old version
#  flutter_speed_dial: ^6.2.0
  flutter_speed_dial: ^1.2.5
  autocomplete_textfield: ^2.0.1
  shared_preferences: ^2.0.15
  crypto: any
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.11
  open_file: ^3.0.1
  tutorial_coach_mark: ^1.2.4
  #dropdownfield: 1.0.3
#  google_fonts: ^3.0.1
  flutter_typeahead: ^3.0.0-nullsafety.0
  #flutter_typeahead: ^4.1.1
  #flash: ^2.0.3
  #old version
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.0

#  image_picker: ^0.8.6
#  image_cropper: ^3.0.1
  circular_profile_avatar: ^2.0.0
  flutter_easyloading: ^3.0.3
  #old version
#  fl_chart: ^0.55.2
  fl_chart: ^0.40.2
  intl: ^0.17.0
  convex_bottom_bar: ^3.0.0
  bottom_navy_bar: ^6.0.0
  fab_circular_menu: ^1.0.2
  data_connection_checker: ^0.3.4
  flutter_launcher_icons: ^0.11.0
  intl_phone_field: ^3.0.1
  #table_calendar: ^3.0.8
  #old version
  table_calendar: ^2.2.3
  #old version
#  flutter_slidable: ^2.0.0
  flutter_slidable: ^0.5.7
  #old version
  flutter_local_notifications: ^4.0.1+2
  cron:
  fluttertoast: ^8.0.9
  badges: ^2.0.3
  hover_effect: ^0.6.0
  percent_indicator: ^4.2.2
  razorpay_flutter: ^1.3.0
  hand_signature: ^2.3.0+1
  responsive_framework: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #old version uncommand remainder
#  build_runner: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  #old version-00
  connectivity_plus: ^0.6.0
  hive_generator: ^2.0.0
  #flash: ^2.0.5



flutter_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/flight_bg.png
    - assets/images/drawer_header_background.png
    - assets/images/othercharge_background.gif
    - assets/anim/rooster.flr
    - assets/airportCode.json
    - assets/specialcode.json
    - assets/countrycode.json
    - assets/airlinecode.json
    - assets/wallet.gif
    - assets/homescreen/dashboard.png
    - assets/homescreen/user_management.png
    - assets/homescreen/configuration.png
    - assets/homescreen/social.png
    - assets/homescreen/hawb.png
    - assets/homescreen/eawb.png
    - assets/homescreen/ehouse.png
    - assets/homescreen/emanifest.webp
    - assets/homescreen/flight.png
    - assets/homescreen/iataedi.png
    - assets/homescreen/iatacargoxml.png
    - assets/homescreen/slot_booking.png
    - assets/homescreen/about.png
    - assets/homescreen/chatbox.png
    - assets/homescreen/todolist.png
    - assets/homescreen/policies.png
    - assets/homescreen/payment_wallet.png
    - assets/dashboard/user.png
    - assets/dashboard/connection.png
    - assets/dashboard/unique_visitors.png
    - assets/dashboard/Booked_AWB.png
    - assets/dashboard/online.png
    - assets/dashboard/table.png
    - assets/dashboard/flights.png
    - assets/dashboard/bounce_rate.png
    - assets/profile/camera.png
    - assets/profile/galery.png
    - assets/profile/default.png
    - assets/homescreen/telax.png
    - assets/dock&slot/vehicle.jpg
    - assets/plan/plan.gif
    - assets/plan/background_plan.gif
    - assets/recharge_wallet/success_payment.gif
    - assets/recharge_wallet/recharge_wallet.gif
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: avenir
      fonts:
        - asset: assets/font/Avenir-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
